### ISSUE TITLE
Add ability to get JPad rules count

### ISSUE THREAD

**Issue by OrRosenblatt** [Soluto/Tweek.JPad#16]
Add support to get JPad rules total count when passing JPad file or providing JPad url.

Suggested solution: 
NPM client that will provide some utils functionality for JPad files.

**Comment by nataly87s** [comment]
Add jpad-tools npm package.
it should expose a `getRulesCount` method that gets a jpad and returns the rules count

**Comment by nataly87s** [comment]
We will add a package in the future, for now you can use this: https://gist.github.com/nataly87s/644f317d3b73144f1bc17c44cadab3b7
